name: CICD Pipeline

on:
  workflow_run:
      workflows: ["Test"]
      types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install
      run: |
        make install

    - name: Generate report
      run: |
        make run

    - name: Deploy
      run: |
        make deploy
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
