name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install
      run: |
        make install

    - name: Lints code with Ruff
      run: |
        make lint

    - name: Formats code with Python black
      run: |
        make format

    - name: Run all tests
      run: |
        make test

    - name: Generate report
      run: |
        make run

    - name: Deploy
      run: |
        make deploy
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
