name: Test

on:
  workflow_run:
    workflows: ["Ruff"]
    types:
      - completed

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install
        run: |
          make install

      - name: Format code
        run: |
          make format

      - name: lint code
        run: |
          make lint

      - name: Run tests
        run: |
          make test
